version: "3"

services:
  proxy:
    hostname: proxy
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy/vhost.d:/etc/nginx/vhost.d"
      - "./proxy/custom.conf:/etc/nginx/conf.d/custom.conf"
      - "/usr/share/nginx/html"
      - html:/usr/share/nginx/html
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - "./proxy/certs:/etc/nginx/certs:ro"
    networks:
      - frontend

  ssl:
    hostname: ssl
    container_name: ssl
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on: [proxy]
    volumes:
      - "./proxy/certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./proxy/vhost.d:/etc/nginx/vhost.d"
      - html:/usr/share/nginx/html
    networks:
      - frontend

networks:
  frontend:
    driver: bridge

volumes:
  html:
