version: "3"

services:
  phpmyadmin:
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    volumes:
      - /sessions
    networks:
      - backend
    environment:
      VIRTUAL_HOST: "${PHPMYADMIN_VIRTUAL_HOST}"
      PMA_HOST: "${DB_HOST}"

networks:
  frontend:
    driver: bridge

volumes:
  html:
